main: com.rooxchicken.psychis.Psychis
name: PsychisPlugin
version: 0.1
api-version: '1.20'

commands:
   hdn_ability1_srt:
      description: First ability START
      usage: /hdn_ability1_srt

   hdn_ability2_srt:
      description: Second ability START
      usage: /hdn_ability2_srt

   hdn_ability1_rpt:
         description: First ability REPEAT
         usage: /hdn_ability1_rpt

   hdn_ability2_rpt:
         description: Second ability REPEAT
         usage: /hdn_ability2_rpt

   hdn_ability1_end:
         description: First ability END
         usage: /hdn_ability1_end
         
   hdn_ability2_end:
      description: Second ability END
      usage: /hdn_ability2_end

   hdn_verifymod:
      description: Client verification of mod
      usage: /hdn_verifymod

   hdn_pickability:
      description: Picks the ability from the gui
      usage: /hdn_pickability <ability>

   selectability:
      description: Opens the ability selector (only if closed)
      usage: /selectability

   ptest:
      description: Particle testing
      usage: /ptest

   resetcooldown:
      description: Resets the cooldown for abilities
      usage: /resetcooldown

   setability:
      description: Sets the selected ability
      usage: /setability <ability> <secondunlocked>

   hdn_openmenu:
      description: For re-selection item. OP only
      usage: /hdn_openmemu <player>

   giveitems:
      description: Gives items
      usage: /giveitems

depend: [ ProtocolLib ]